# Tensor Basics

Based on **Patric Loeber** video: https://www.youtube.com/watch?v=c36lUUr864M&t=450s

## Tensor

### Notes

tensors can have different dimensions: 1d, 2d, 3d or more.

## Creating tensors

In [1]:
import torch

In [12]:
# empty tensor, we have to specify the size
# like 1d vector with 3 elements
x = torch.empty(3)
# like 2d matrix
x = torch.empty(2, 3)
# 3d tensor
x = torch.empty(2, 2, 3)
# 4d tensor
x = torch.empty(2, 2, 2, 3)
print(x)

tensor([[[[0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.]]],


        [[[0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.]]]])


In [15]:
# tensor with random values
x = torch.rand(2, 2)
print(x)

tensor([[0.0404, 0.7200],
        [0.6809, 0.9980]])


In [17]:
# tensor filled with 0'es
x = torch.zeros(2, 2)
print(x)

tensor([[0., 0.],
        [0., 0.]])


In [19]:
# tensor filled with 1's
x = torch.ones(2,2)
print(x)

tensor([[1., 1.],
        [1., 1.]])


In [24]:
# we can give it specific data type, by default float32
x = torch.ones(2,2, dtype=torch.float16) # int, double, torch.float16
# checking tensor type
print(x.dtype)
# checking tensor size
print(x.size())

torch.float16
torch.Size([2, 2])


In [25]:
# creating tensor from data
x = torch.tensor([2.5, 0.1])
print(x)

tensor([2.5000, 0.1000])


## Basic operations

In [26]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)
print(x)
print(y)

tensor([[0.5338, 0.1326],
        [0.6988, 0.0970]])
tensor([[0.0869, 0.1482],
        [0.3593, 0.6663]])


In [34]:
# element wise addition
z = x + y
print(z)
z = torch.add(x,y)
print(z)
# in place addition
y.add_(x)
print(y)

tensor([[0.6207, 0.2808],
        [1.0582, 0.7633]])
tensor([[0.6207, 0.2808],
        [1.0582, 0.7633]])
tensor([[0.6207, 0.2808],
        [1.0582, 0.7633]])


In pytorch every function with trailing underscore will do an inplace operation, will modify the variable that it is applied on.

In [35]:
# subtraction
z = x - y
print(z)
z = torch.sub(x,y)
print(z)
# in place subtraction
y.sub_(x)
print(y)

tensor([[-0.0869, -0.1482],
        [-0.3593, -0.6663]])
tensor([[-0.0869, -0.1482],
        [-0.3593, -0.6663]])
tensor([[0.0869, 0.1482],
        [0.3593, 0.6663]])


In [36]:
# multiplying
z = x * y
print(z)
z = torch.mul(x,y)
print(z)
y.mul_(x)
print(y)

tensor([[0.0464, 0.0197],
        [0.2511, 0.0646]])
tensor([[0.0464, 0.0197],
        [0.2511, 0.0646]])
tensor([[0.0464, 0.0197],
        [0.2511, 0.0646]])


In [37]:
# dividing
z = x / y
print(z)
z = torch.div(x,y)
print(z)
y.div_(x)
print(y)

tensor([[11.5078,  6.7470],
        [ 2.7830,  1.5008]])
tensor([[11.5078,  6.7470],
        [ 2.7830,  1.5008]])
tensor([[0.0869, 0.1482],
        [0.3593, 0.6663]])


## Slicing operations

In [46]:
x = torch.rand(5, 3)
print('1.',x)
# all rows and column 1
print('2.',x[:, 0])
# row 1 and all calumns
print('3.',x[1, :])
# tensor element on position 1 1
print('4.',x[1, 1])
# actual value, we can use this if we have only one element in our tensor
print('5.',x[1, 1].item())

1. tensor([[0.4085, 0.5641, 0.3783],
        [0.6851, 0.0694, 0.3157],
        [0.9099, 0.7571, 0.9710],
        [0.9945, 0.6359, 0.7382],
        [0.1441, 0.2253, 0.9300]])
2. tensor([0.4085, 0.6851, 0.9099, 0.9945, 0.1441])
3. tensor([0.6851, 0.0694, 0.3157])
4. tensor(0.0694)
5. 0.06942307949066162


## Reshaping a tensor

Number of elements must still be the same.

In [50]:
x = torch.rand(4,4)
print('1.',x)
# 1d vector
y = x.view(16)
print('2.',y)
# by specifing -1 the PyTorch has to figure right size for itself
# in this case it will be 2 by 8
y = x.view(-1, 8)
print('3.',y)

1. tensor([[0.5861, 0.2394, 0.6677, 0.9760],
        [0.0062, 0.2056, 0.9046, 0.5796],
        [0.2250, 0.2053, 0.1693, 0.7439],
        [0.6966, 0.5818, 0.2002, 0.4839]])
2. tensor([0.5861, 0.2394, 0.6677, 0.9760, 0.0062, 0.2056, 0.9046, 0.5796, 0.2250,
        0.2053, 0.1693, 0.7439, 0.6966, 0.5818, 0.2002, 0.4839])


## Converting from numpy to torch tensor and vice versa

In [51]:
import numpy as np

In [55]:
a = torch.ones(5)
print('1.', a)
# converting tensor to numpy array
b = a.numpy()
print('2.', b)
print('3.', type(b))

1. tensor([1., 1., 1., 1., 1.])
2. [1. 1. 1. 1. 1.]
3. <class 'numpy.ndarray'>


### Notes

we have to be careful because if the tensor is on the cpu and not the gpu then both objects will share the same memory location. This means that if we change one we will also change the other. If we modify b or a inplace then we will also modify another one. That's because they both point to the same memory

In [59]:
a.add_(1)
print(a)
print(b)

tensor([3., 3., 3., 3., 3.])
[3. 3. 3. 3. 3.]


In [63]:
# converting numpy array to tensor
# by default it will be data type float64
a = np.ones(5)
print('1.', a)
b = torch.from_numpy(a)
print('2.', b)

1. [1. 1. 1. 1. 1.]
2. tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [64]:
# same situation here, modifying one will also modify second one.
# This happen only if tensor is on the cpu
a += 1
print('1.', a)
print('2.', b)

1. [2. 2. 2. 2. 2.]
2. tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


## Using GPU

We can't convert a gpu tensor back to numpy because numpy can only handle cpu tensors.

In [70]:
# checking if we have gpu and then specifying device and creating tensor on gpu
if torch.cuda.is_available():
    device = torch.device("cuda")
    # specifing device
    x = torch.ones(5, device=device)
    y = torch.ones(5)
    # moving our tensor to device
    y = y.to(device)
    # should be preformed on GPU and be much faster
    z = x + y
    # z.nupmy() will rise an error because numpy can only handle cpu tensors
    # we have to change device to cpu
    z = z.to("cpu")

In [73]:
print('1.', x)
print('2.', y)
print('3.', z)

1. tensor([1., 1., 1., 1., 1.], device='cuda:0')
2. tensor([1., 1., 1., 1., 1.], device='cuda:0')
3. tensor([2., 2., 2., 2., 2.])


## Requires_gradf

A lot of times when a tensor is created we see the argument requires_grad=True (by default it is False). After printing we will also see that requires_grad=True. This will tell PyTorch that it will need to calculate the gradients for this tensor later in our optimization steps. This means that whenever we have a variable in our model that we want to optimize then we need the gradients. So we need to specify requires_grad=True.

In [74]:
x = torch.ones(5, requires_grad=True)
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)
