# Scikit-Learn Cours - Machine Learning

By freeCodeCamp.org

https://www.youtube.com/watch?v=pqNCD_5r0IU&list=PLY8_mf17J6TIGNwBjKW3t1Pwdb59t30Kt&index=7&t=2s


## Train Test Split

In [1]:
from sklearn import datasets
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
iris = datasets.load_iris()

# split it in features and labels
X = iris.data
y = iris.target

print(f"Features:\n{X[:5]}\n...\n\nLabels:\n{y[:5]}\n...")

Features:
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
...

Labels:
[0 0 0 0 0]
...


In [3]:
print(X.shape)
print(y.shape)


(150, 4)
(150,)


In [4]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(120, 4)
(30, 4)
(120,)
(30,)


## KNN Example

In [5]:
import numpy as np
import pandas as pd
from sklearn import neighbors, metrics
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [6]:
data = pd.read_csv("knn_classifier/car.data")

In [7]:
print(data.head())

  buying  maint doors persons lug_boot safety  class
0  vhigh  vhigh     2       2    small    low  unacc
1  vhigh  vhigh     2       2    small    med  unacc
2  vhigh  vhigh     2       2    small   high  unacc
3  vhigh  vhigh     2       2      med    low  unacc
4  vhigh  vhigh     2       2      med    med  unacc


In [8]:
last_column_label = data.columns[-1]
y = data[last_column_label].copy().to_frame(name=last_column_label)
X = data.drop(columns=[last_column_label])

In [9]:
print(f"X sample:\n{X.head()}\n\ny sample:\n{y.head()}")

X sample:
  buying  maint doors persons lug_boot safety
0  vhigh  vhigh     2       2    small    low
1  vhigh  vhigh     2       2    small    med
2  vhigh  vhigh     2       2    small   high
3  vhigh  vhigh     2       2      med    low
4  vhigh  vhigh     2       2      med    med

y sample:
   class
0  unacc
1  unacc
2  unacc
3  unacc
4  unacc


### Converting the data

In [10]:
X = X.values
Le = LabelEncoder()
for i in range(X.shape[1]):
    X[:, i] = Le.fit_transform(X[:, i])

In [11]:
print(X)

[[3 3 0 0 2 1]
 [3 3 0 0 2 2]
 [3 3 0 0 2 0]
 ...
 [1 1 3 2 0 1]
 [1 1 3 2 0 2]
 [1 1 3 2 0 0]]


In [12]:
#y
label_mapping = {
  'unacc':0,
  'acc':1,
  'good':2,
  'vgood':3
 }
y['class'] = y['class'].map(label_mapping)
Y = np.array(y)

In [13]:
print(y)

      class
0         0
1         0
2         0
3         0
4         0
...     ...
1723      2
1724      3
1725      0
1726      2
1727      3

[1728 rows x 1 columns]


### Create model

In [23]:
knn = neighbors.KNeighborsClassifier(
    n_neighbors=25,
    weights='uniform'
)
# somethign about 37 check comments

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

knn.fit(X_train, y_train)

predictions = knn.predict(X_test)

accuracy = metrics.accuracy_score(y_test, predictions)

print(f"Predictions: {predictions}")
print(f"Accuracy : {accuracy}")

a = 345
# check why is not working
# print(f"actual value: {y[a]}, predicted value: {knn.predict(X[a])}")
print(f"actual value: {y.loc[a, 'class']}, predicted value: {predictions[a]}")

Predictions: [0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 1 0 0 1 0 1 0 0 0 0 0 0 0 0
 0 0 0 0 3 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 1 1 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 3 0 0 0 0 3 0 0 0 0 0 0 1 1 1 1 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 3
 1 0 1 0 0 0 0 0 2 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 1 0 3 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 1 3 0 0
 0 0 1 0 1 0 0 0 0 0 0 0 0]
Accuracy : 0.8121387283236994
actual value: 0, predicted value: 0


/Users/florian/anaconda3/lib/python3.10/site-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
